## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: PaperColor Dark
# Scheme author: Jon Leopard (http://github.com/jonleopard), Tinted Theming (https://github.com/tinted-theming), based on PaperColor Theme (https://github.com/NLKNguyen/papercolor-theme)
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)



"text"      = { fg = "#9e9e9e", bg = "#1c1c1c" }
"dimmed"    = { fg = "#585858", bg = "#1c1c1c" }
"title"     = { fg = "#5fafd7", bold = true }
"shortcut"  = { fg = "#af87d7" }
"matched"   = { fg = "#ffaf00" }
"border"    = { fg = "#585858" }
"selected"  = { bg = "#363636", fg = "#9e9e9e", bold = true }

"source_marker" = { bg = "#00afaf", fg = "#1c1c1c", bold = true }
"target_marker" = { bg = "#5faf5f", fg = "#1c1c1c", bold = true }

"status" = { bg = "#363636" }
"status title" = { fg = "#1c1c1c", bg = "#5fafd7", bold = true }

"revset title" = { fg = "#5fafd7", bold = true }
"revset text" = { fg = "#9e9e9e", bold = true }
"revset completion text" = { fg = "#9e9e9e" }
"revset completion matched" = { fg = "#ffaf00", bold = true }
"revset completion dimmed" = { fg = "#585858" }
"revset completion selected" = { bg = "#424242", fg = "#9e9e9e" }

"revisions" = { fg = "#9e9e9e" }
"revisions selected" = { bg = "#363636"}
"revisions dimmed" = { fg = "#585858" }
"revisions details selected" = { bg = "#424242" }
"oplog selected" = { bold = true }

"evolog" = { fg = "#9e9e9e" }
"evolog selected" = { bg = "#424242", fg = "#9e9e9e", bold = true }

"menu" = { bg = "#1c1c1c" }
"menu title" = { fg = "#1c1c1c", bg = "#af87d7", bold = true }
"menu shortcut" = { fg = "#af87d7" }
"menu matched" = { fg = "#ffaf00", bold = true }
"menu dimmed" = { fg = "#585858" }
"menu border" = { fg = "#363636" }
"menu selected" = { bg = "#424242", fg = "#9e9e9e" }

"help" = { bg = "#1c1c1c" }
"help title" = { fg = "#5faf5f", bold = true, underline = true }
"help border" = { fg = "#363636" }

"preview" = { fg = "#9e9e9e" }
"preview border" = { fg = "#363636" }

"confirmation" = { bg = "#1c1c1c" }
"confirmation text" = { fg = "#5fafd7", bold = true }
"confirmation dimmed" = { fg = "#585858" }
"confirmation border" = { fg = "#ff5faf", bold = true }
"confirmation selected" = { bg = "#424242", fg = "#9e9e9e" }

"undo" = { bg = "#1c1c1c" }
"undo confirmation dimmed" = { fg = "#585858" }
"undo confirmation selected" = { bg = "#424242", fg = "#9e9e9e" }

"success" = { fg = "#5faf5f", bold = true }
"error" = { fg = "#ff5faf", bold = true }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"status shortcut" = { fg = "#af87d7" }
"status dimmed" = { fg = "#585858" }

"details" = { fg = "#9e9e9e" }
"details selected" = { bold = true }
"completion" = { fg = "#9e9e9e" }
"completion selected" = { bold = true }
"rebase" = { bold = true }

"workspace" = { fg = "#5fafd7" }
"branch" = { fg = "#d7af5f" }
"commit" = { fg = "#5faf5f" }
"file" = { fg = "#ffaf00" }
"change" = { fg = "#ff5faf" }
"bookmark" = { fg = "#af87d7" }


