## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: Edge Light
# Scheme author: cjayross (https://github.com/cjayross), Tinted Theming (https://github.com/tinted-theming)
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)



"text"      = { fg = "#474752", bg = "#fafafa" }
"dimmed"    = { fg = "#9197a1", bg = "#fafafa" }
"title"     = { fg = "#6587bf", bold = true }
"shortcut"  = { fg = "#b870ce" }
"matched"   = { fg = "#ebcc1a" }
"border"    = { fg = "#9197a1" }
"selected"  = { bg = "#e3e5e8", fg = "#474752", bold = true }

"source_marker" = { bg = "#509c93", fg = "#fafafa", bold = true }
"target_marker" = { bg = "#7c9f4b", fg = "#fafafa", bold = true }

"status" = { bg = "#e3e5e8" }
"status title" = { fg = "#fafafa", bg = "#6587bf", bold = true }

"revset title" = { fg = "#6587bf", bg = "#e3e5e8", bold = true }
"revset text" = { fg = "#474752", bold = true }
"revset completion text" = { fg = "#474752" }
"revset completion matched" = { fg = "#ebcc1a", bold = true }
"revset completion dimmed" = { fg = "#9197a1" }
"revset completion selected" = { bg = "#3a3a46", fg = "#acb1b9" }

"revisions" = { fg = "#474752" }
"revisions selected" = { bg = "#acb1b9"}
"revisions dimmed" = { fg = "#9197a1" }
"revisions details selected" = { bg = "#5e646f" }
"oplog selected" = { bold = true }

"evolog" = { fg = "#474752" }
"evolog selected" = { bg = "#3a3a46", fg = "#e3e5e8", bold = true }

"menu" = { bg = "#fafafa" }
"menu title" = { fg = "#fafafa", bg = "#b870ce", bold = true }
"menu shortcut" = { fg = "#b870ce" }
"menu matched" = { fg = "#ebcc1a", bold = true }
"menu dimmed" = { fg = "#9197a1" }
"menu border" = { fg = "#e3e5e8" }
"menu selected" = { bg = "#3a3a46", fg = "#e3e5e8" }

"help" = { bg = "#fafafa" }
"help title" = { fg = "#7c9f4b", bold = true, underline = true }
"help border" = { fg = "#e3e5e8" }

"preview" = { fg = "#474752" }
"preview border" = { fg = "#e3e5e8" }

"confirmation" = { bg = "#fafafa" }
"confirmation text" = { fg = "#6587bf", bold = true }
"confirmation dimmed" = { fg = "#9197a1" }
"confirmation border" = { fg = "#db7070", bold = true }
"confirmation selected" = { bg = "#3a3a46", fg = "#e3e5e8" }

"undo" = { bg = "#fafafa" }
"undo confirmation dimmed" = { fg = "#9197a1" }
"undo confirmation selected" = { bg = "#3a3a46", fg = "#e3e5e8" }

"success" = { fg = "#7c9f4b", bold = true }
"error" = { fg = "#db7070", bold = true }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"status shortcut" = { fg = "#b870ce" }
"status dimmed" = { fg = "#9197a1" }

"details" = { fg = "#474752" }
"details selected" = { bold = true }
"completion" = { fg = "#474752" }
"completion selected" = { bold = true }
"rebase" = { bold = true }

"workspace" = { fg = "#6587bf" }
"branch" = { fg = "#eba31a" }
"commit" = { fg = "#7c9f4b" }
"file" = { fg = "#ebcc1a" }
"change" = { fg = "#db7070" }
"bookmark" = { fg = "#b870ce" }


