## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: Ocean
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)



"text"      = { fg = "#a8a8a8", bg = "#224fbc" }
"dimmed"    = { fg = "#7c7c7c", bg = "#224fbc" }
"title"     = { fg = "#0000b2", bold = true }
"shortcut"  = { fg = "#b200b2" }
"matched"   = { fg = "#e5e500" }
"border"    = { fg = "#7c7c7c" }
"selected"  = { bg = "#000000", fg = "#a8a8a8", bold = true }

"source_marker" = { bg = "#00e5e5", fg = "#224fbc", bold = true }
"target_marker" = { bg = "#00d900", fg = "#224fbc", bold = true }

"status" = { bg = "#000000" }
"status title" = { fg = "#224fbc", bg = "#0000ff", bold = true }

"revset title" = { fg = "#0000b2", bold = true }
"revset text" = { fg = "#a8a8a8", bold = true }
"revset completion text" = { fg = "#a8a8a8" }
"revset completion matched" = { fg = "#e5e500", bold = true }
"revset completion dimmed" = { fg = "#7c7c7c" }
"revset completion selected" = { bg = "#666666", fg = "#a8a8a8" }

"revisions" = { fg = "#a8a8a8" }
"revisions selected" = { bg = "#000000"}
"revisions dimmed" = { fg = "#7c7c7c" }
"revisions details selected" = { bg = "#666666" }
"oplog selected" = { bold = true }

"evolog" = { fg = "#a8a8a8" }
"evolog selected" = { bg = "#666666", fg = "#a8a8a8", bold = true }

"menu" = { bg = "#224fbc" }
"menu title" = { fg = "#224fbc", bg = "#e500e5", bold = true }
"menu shortcut" = { fg = "#e500e5" }
"menu matched" = { fg = "#e5e500", bold = true }
"menu dimmed" = { fg = "#7c7c7c" }
"menu border" = { fg = "#000000" }
"menu selected" = { bg = "#666666", fg = "#a8a8a8" }

"help" = { bg = "#224fbc" }
"help title" = { fg = "#00d900", bold = true, underline = true }
"help border" = { fg = "#000000" }

"preview" = { fg = "#a8a8a8" }
"preview border" = { fg = "#000000" }

"confirmation" = { bg = "#224fbc" }
"confirmation text" = { fg = "#0000b2", bold = true }
"confirmation dimmed" = { fg = "#7c7c7c" }
"confirmation border" = { fg = "#e50000", bold = true }
"confirmation selected" = { bg = "#666666", fg = "#a8a8a8" }

"undo" = { bg = "#224fbc" }
"undo confirmation dimmed" = { fg = "#7c7c7c" }
"undo confirmation selected" = { bg = "#666666", fg = "#a8a8a8" }

"success" = { fg = "#00d900", bold = true }
"error" = { fg = "#e50000", bold = true }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"status shortcut" = { fg = "#e500e5" }
"status dimmed" = { fg = "#7c7c7c" }

"details" = { fg = "#a8a8a8" }
"details selected" = { bold = true }
"completion" = { fg = "#a8a8a8" }
"completion selected" = { bold = true }
"rebase" = { bold = true }

"workspace" = { fg = "#0000ff" }
"branch" = { fg = "#00e5e5" }
"commit" = { fg = "#00d900" }
"file" = { fg = "#e5e500" }
"change" = { fg = "#e50000" }
"bookmark" = { fg = "#e500e5" }


