## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: Catppuccin Latte
# Scheme author: https://github.com/catppuccin/catppuccin
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)



"text"      = { fg = "#4c4f69", bg = "#eff1f5" }
"dimmed"    = { fg = "#9ca0b0", bg = "#eff1f5" }
"title"     = { fg = "#1e66f5", bold = true }
"shortcut"  = { fg = "#8839ef" }
"matched"   = { fg = "#df8e1d" }
"border"    = { fg = "#9ca0b0" }
"selected"  = { bg = "#ccd0da", fg = "#4c4f69", bold = true }

"source_marker" = { bg = "#179299", fg = "#eff1f5", bold = true }
"target_marker" = { bg = "#40a02b", fg = "#eff1f5", bold = true }

"status" = { bg = "#ccd0da" }
"status title" = { fg = "#eff1f5", bg = "#1e66f5", bold = true }

"revset title" = { fg = "#1e66f5", bg = "#ccd0da", bold = true }
"revset text" = { fg = "#4c4f69", bold = true }
"revset completion text" = { fg = "#4c4f69" }
"revset completion matched" = { fg = "#df8e1d", bold = true }
"revset completion dimmed" = { fg = "#9ca0b0" }
"revset completion selected" = { bg = "#dc8a78", fg = "#bcc0cc" }

"revisions" = { fg = "#4c4f69" }
"revisions selected" = { bg = "#bcc0cc"}
"revisions dimmed" = { fg = "#9ca0b0" }
"revisions details selected" = { bg = "#6c6f85" }
"oplog selected" = { bold = true }

"evolog" = { fg = "#4c4f69" }
"evolog selected" = { bg = "#dc8a78", fg = "#ccd0da", bold = true }

"menu" = { bg = "#eff1f5" }
"menu title" = { fg = "#eff1f5", bg = "#8839ef", bold = true }
"menu shortcut" = { fg = "#8839ef" }
"menu matched" = { fg = "#df8e1d", bold = true }
"menu dimmed" = { fg = "#9ca0b0" }
"menu border" = { fg = "#ccd0da" }
"menu selected" = { bg = "#dc8a78", fg = "#ccd0da" }

"help" = { bg = "#eff1f5" }
"help title" = { fg = "#40a02b", bold = true, underline = true }
"help border" = { fg = "#ccd0da" }

"preview" = { fg = "#4c4f69" }
"preview border" = { fg = "#ccd0da" }

"confirmation" = { bg = "#eff1f5" }
"confirmation text" = { fg = "#1e66f5", bold = true }
"confirmation dimmed" = { fg = "#9ca0b0" }
"confirmation border" = { fg = "#d20f39", bold = true }
"confirmation selected" = { bg = "#dc8a78", fg = "#ccd0da" }

"undo" = { bg = "#eff1f5" }
"undo confirmation dimmed" = { fg = "#9ca0b0" }
"undo confirmation selected" = { bg = "#dc8a78", fg = "#ccd0da" }

"success" = { fg = "#40a02b", bold = true }
"error" = { fg = "#d20f39", bold = true }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"status shortcut" = { fg = "#8839ef" }
"status dimmed" = { fg = "#9ca0b0" }

"details" = { fg = "#4c4f69" }
"details selected" = { bold = true }
"completion" = { fg = "#4c4f69" }
"completion selected" = { bold = true }
"rebase" = { bold = true }

"workspace" = { fg = "#1e66f5" }
"branch" = { fg = "#fe640b" }
"commit" = { fg = "#40a02b" }
"file" = { fg = "#df8e1d" }
"change" = { fg = "#d20f39" }
"bookmark" = { fg = "#8839ef" }


