## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: Tango Adapted
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)



"text"      = { fg = "#4f4f4f", bg = "#feffff" }
"dimmed"    = { fg = "#cccccc", bg = "#feffff" }
"title"     = { fg = "#00a1ff", bold = true }
"shortcut"  = { fg = "#c17ecb" }
"matched"   = { fg = "#fff021" }
"border"    = { fg = "#cccccc" }
"selected"  = { bg = "#f1f1f1", fg = "#4f4f4f", bold = true }

"source_marker" = { bg = "#00fdff", fg = "#feffff", bold = true }
"target_marker" = { bg = "#93fe00", fg = "#feffff", bold = true }

"status" = { bg = "#f1f1f1" }
"status title" = { fg = "#feffff", bg = "#88c9ff", bold = true }

"revset title" = { fg = "#00a1ff", bg = "#f1f1f1", bold = true }
"revset text" = { fg = "#4f4f4f", bold = true }
"revset completion text" = { fg = "#4f4f4f" }
"revset completion matched" = { fg = "#fff021", bold = true }
"revset completion dimmed" = { fg = "#cccccc" }
"revset completion selected" = { bg = "#323232", fg = "#dcdcdc" }

"revisions" = { fg = "#4f4f4f" }
"revisions selected" = { bg = "#dcdcdc"}
"revisions dimmed" = { fg = "#cccccc" }
"revisions details selected" = { bg = "#757575" }
"oplog selected" = { bold = true }

"evolog" = { fg = "#4f4f4f" }
"evolog selected" = { bg = "#323232", fg = "#f1f1f1", bold = true }

"menu" = { bg = "#feffff" }
"menu title" = { fg = "#feffff", bg = "#e8a6e1", bold = true }
"menu shortcut" = { fg = "#e8a6e1" }
"menu matched" = { fg = "#fff021", bold = true }
"menu dimmed" = { fg = "#cccccc" }
"menu border" = { fg = "#f1f1f1" }
"menu selected" = { bg = "#323232", fg = "#f1f1f1" }

"help" = { bg = "#feffff" }
"help title" = { fg = "#93fe00", bold = true, underline = true }
"help border" = { fg = "#f1f1f1" }

"preview" = { fg = "#4f4f4f" }
"preview border" = { fg = "#f1f1f1" }

"confirmation" = { bg = "#feffff" }
"confirmation text" = { fg = "#00a1ff", bold = true }
"confirmation dimmed" = { fg = "#cccccc" }
"confirmation border" = { fg = "#ff0012", bold = true }
"confirmation selected" = { bg = "#323232", fg = "#f1f1f1" }

"undo" = { bg = "#feffff" }
"undo confirmation dimmed" = { fg = "#cccccc" }
"undo confirmation selected" = { bg = "#323232", fg = "#f1f1f1" }

"success" = { fg = "#93fe00", bold = true }
"error" = { fg = "#ff0012", bold = true }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"status shortcut" = { fg = "#e8a6e1" }
"status dimmed" = { fg = "#cccccc" }

"details" = { fg = "#4f4f4f" }
"details selected" = { bold = true }
"completion" = { fg = "#4f4f4f" }
"completion selected" = { bold = true }
"rebase" = { bold = true }

"workspace" = { fg = "#88c9ff" }
"branch" = { fg = "#00fdff" }
"commit" = { fg = "#93fe00" }
"file" = { fg = "#fff021" }
"change" = { fg = "#ff0012" }
"bookmark" = { fg = "#e8a6e1" }


