## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: Charcoal Light
# Scheme author: Mubin Muhammad (https://github.com/mubin6th)
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)



"text"      = { fg = "#382e1b", bg = "#cabda0" }
"dimmed"    = { fg = "#645538", bg = "#cabda0" }
"title"     = { fg = "#251e0f", bold = true }
"shortcut"  = { fg = "#382e1b" }
"matched"   = { fg = "#110e06" }
"border"    = { fg = "#645538" }
"selected"  = { bg = "#bcad8c", fg = "#382e1b", bold = true }

"source_marker" = { bg = "#110e06", fg = "#cabda0", bold = true }
"target_marker" = { bg = "#110e06", fg = "#cabda0", bold = true }

"status" = { bg = "#bcad8c" }
"status title" = { fg = "#cabda0", bg = "#251e0f", bold = true }

"revset title" = { fg = "#251e0f", bg = "#bcad8c", bold = true }
"revset text" = { fg = "#382e1b", bold = true }
"revset completion text" = { fg = "#382e1b" }
"revset completion matched" = { fg = "#110e06", bold = true }
"revset completion dimmed" = { fg = "#645538" }
"revset completion selected" = { bg = "#4b3e26", fg = "#af9f7d" }

"revisions" = { fg = "#382e1b" }
"revisions selected" = { bg = "#af9f7d"}
"revisions dimmed" = { fg = "#645538" }
"revisions details selected" = { bg = "#110e06" }
"oplog selected" = { bold = true }

"evolog" = { fg = "#382e1b" }
"evolog selected" = { bg = "#4b3e26", fg = "#bcad8c", bold = true }

"menu" = { bg = "#cabda0" }
"menu title" = { fg = "#cabda0", bg = "#382e1b", bold = true }
"menu shortcut" = { fg = "#382e1b" }
"menu matched" = { fg = "#110e06", bold = true }
"menu dimmed" = { fg = "#645538" }
"menu border" = { fg = "#bcad8c" }
"menu selected" = { bg = "#4b3e26", fg = "#bcad8c" }

"help" = { bg = "#cabda0" }
"help title" = { fg = "#110e06", bold = true, underline = true }
"help border" = { fg = "#bcad8c" }

"preview" = { fg = "#382e1b" }
"preview border" = { fg = "#bcad8c" }

"confirmation" = { bg = "#cabda0" }
"confirmation text" = { fg = "#251e0f", bold = true }
"confirmation dimmed" = { fg = "#645538" }
"confirmation border" = { fg = "#382e1b", bold = true }
"confirmation selected" = { bg = "#4b3e26", fg = "#bcad8c" }

"undo" = { bg = "#cabda0" }
"undo confirmation dimmed" = { fg = "#645538" }
"undo confirmation selected" = { bg = "#4b3e26", fg = "#bcad8c" }

"success" = { fg = "#110e06", bold = true }
"error" = { fg = "#382e1b", bold = true }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"status shortcut" = { fg = "#382e1b" }
"status dimmed" = { fg = "#645538" }

"details" = { fg = "#382e1b" }
"details selected" = { bold = true }
"completion" = { fg = "#382e1b" }
"completion selected" = { bold = true }
"rebase" = { bold = true }

"workspace" = { fg = "#251e0f" }
"branch" = { fg = "#110e06" }
"commit" = { fg = "#110e06" }
"file" = { fg = "#110e06" }
"change" = { fg = "#382e1b" }
"bookmark" = { fg = "#382e1b" }


