## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: Wryan
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)



"text"      = { fg = "#768488", bg = "#101010" }
"dimmed"    = { fg = "#505456", bg = "#101010" }
"title"     = { fg = "#395573", bold = true }
"shortcut"  = { fg = "#5e468c" }
"matched"   = { fg = "#9e9ecb" }
"border"    = { fg = "#505456" }
"selected"  = { bg = "#333333", fg = "#768488", bold = true }

"source_marker" = { bg = "#6096bf", fg = "#101010", bold = true }
"target_marker" = { bg = "#53a6a6", fg = "#101010", bold = true }

"status" = { bg = "#333333" }
"status title" = { fg = "#101010", bg = "#477ab3", bold = true }

"revset title" = { fg = "#395573", bold = true }
"revset text" = { fg = "#768488", bold = true }
"revset completion text" = { fg = "#768488" }
"revset completion matched" = { fg = "#9e9ecb", bold = true }
"revset completion dimmed" = { fg = "#505456" }
"revset completion selected" = { bg = "#3d3d3d", fg = "#768488" }

"revisions" = { fg = "#768488" }
"revisions selected" = { bg = "#333333"}
"revisions dimmed" = { fg = "#505456" }
"revisions details selected" = { bg = "#3d3d3d" }
"oplog selected" = { bold = true }

"evolog" = { fg = "#768488" }
"evolog selected" = { bg = "#3d3d3d", fg = "#768488", bold = true }

"menu" = { bg = "#101010" }
"menu title" = { fg = "#101010", bg = "#7e62b3", bold = true }
"menu shortcut" = { fg = "#7e62b3" }
"menu matched" = { fg = "#9e9ecb", bold = true }
"menu dimmed" = { fg = "#505456" }
"menu border" = { fg = "#333333" }
"menu selected" = { bg = "#3d3d3d", fg = "#768488" }

"help" = { bg = "#101010" }
"help title" = { fg = "#53a6a6", bold = true, underline = true }
"help border" = { fg = "#333333" }

"preview" = { fg = "#768488" }
"preview border" = { fg = "#333333" }

"confirmation" = { bg = "#101010" }
"confirmation text" = { fg = "#395573", bold = true }
"confirmation dimmed" = { fg = "#505456" }
"confirmation border" = { fg = "#bf4d80", bold = true }
"confirmation selected" = { bg = "#3d3d3d", fg = "#768488" }

"undo" = { bg = "#101010" }
"undo confirmation dimmed" = { fg = "#505456" }
"undo confirmation selected" = { bg = "#3d3d3d", fg = "#768488" }

"success" = { fg = "#53a6a6", bold = true }
"error" = { fg = "#bf4d80", bold = true }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"status shortcut" = { fg = "#7e62b3" }
"status dimmed" = { fg = "#505456" }

"details" = { fg = "#768488" }
"details selected" = { bold = true }
"completion" = { fg = "#768488" }
"completion selected" = { bold = true }
"rebase" = { bold = true }

"workspace" = { fg = "#477ab3" }
"branch" = { fg = "#6096bf" }
"commit" = { fg = "#53a6a6" }
"file" = { fg = "#9e9ecb" }
"change" = { fg = "#bf4d80" }
"bookmark" = { fg = "#7e62b3" }


