## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: Ascendancy
# Scheme author: EmergentMind (https://github.com/emergentmind/ascendancy-scheme)
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)



"text"      = { fg = "#d5c7a1", bg = "#282828" }
"dimmed"    = { fg = "#928374", bg = "#282828" }
"title"     = { fg = "#458588", bold = true }
"shortcut"  = { fg = "#fabd2f" }
"matched"   = { fg = "#ffcc1b" }
"border"    = { fg = "#928374" }
"selected"  = { bg = "#212f3d", fg = "#d5c7a1", bold = true }

"source_marker" = { bg = "#8f3f71", fg = "#282828", bold = true }
"target_marker" = { bg = "#b8bb26", fg = "#282828", bold = true }

"status" = { bg = "#212f3d" }
"status title" = { fg = "#282828", bg = "#458588", bold = true }

"revset title" = { fg = "#458588", bold = true }
"revset text" = { fg = "#d5c7a1", bold = true }
"revset completion text" = { fg = "#d5c7a1" }
"revset completion matched" = { fg = "#ffcc1b", bold = true }
"revset completion dimmed" = { fg = "#928374" }
"revset completion selected" = { bg = "#504945", fg = "#d5c7a1" }

"revisions" = { fg = "#d5c7a1" }
"revisions selected" = { bg = "#212f3d"}
"revisions dimmed" = { fg = "#928374" }
"revisions details selected" = { bg = "#504945" }
"oplog selected" = { bold = true }

"evolog" = { fg = "#d5c7a1" }
"evolog selected" = { bg = "#504945", fg = "#d5c7a1", bold = true }

"menu" = { bg = "#282828" }
"menu title" = { fg = "#282828", bg = "#fabd2f", bold = true }
"menu shortcut" = { fg = "#fabd2f" }
"menu matched" = { fg = "#ffcc1b", bold = true }
"menu dimmed" = { fg = "#928374" }
"menu border" = { fg = "#212f3d" }
"menu selected" = { bg = "#504945", fg = "#d5c7a1" }

"help" = { bg = "#282828" }
"help title" = { fg = "#b8bb26", bold = true, underline = true }
"help border" = { fg = "#212f3d" }

"preview" = { fg = "#d5c7a1" }
"preview border" = { fg = "#212f3d" }

"confirmation" = { bg = "#282828" }
"confirmation text" = { fg = "#458588", bold = true }
"confirmation dimmed" = { fg = "#928374" }
"confirmation border" = { fg = "#c03900", bold = true }
"confirmation selected" = { bg = "#504945", fg = "#d5c7a1" }

"undo" = { bg = "#282828" }
"undo confirmation dimmed" = { fg = "#928374" }
"undo confirmation selected" = { bg = "#504945", fg = "#d5c7a1" }

"success" = { fg = "#b8bb26", bold = true }
"error" = { fg = "#c03900", bold = true }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"status shortcut" = { fg = "#fabd2f" }
"status dimmed" = { fg = "#928374" }

"details" = { fg = "#d5c7a1" }
"details selected" = { bold = true }
"completion" = { fg = "#d5c7a1" }
"completion selected" = { bold = true }
"rebase" = { bold = true }

"workspace" = { fg = "#458588" }
"branch" = { fg = "#fe8019" }
"commit" = { fg = "#b8bb26" }
"file" = { fg = "#ffcc1b" }
"change" = { fg = "#c03900" }
"bookmark" = { fg = "#fabd2f" }


